---
# Run the Prechecks part of JPxConf
- name: Running JPxConf - Prechecks
  import_playbook: prechecks.yml
  tags: prechecks

# Run the Provisioning part of JPxConf
- name: Running JPxConf - Provisioning
  import_playbook: provisioning.yml
  tags: provisioning

# Run the Deploy part of JPxConf
- name: Running JPxConf - Deploy
  import_playbook: deploy.yml
  tags: deploy