---
# Checking connectivity to inventory hosts
- name: Connectivity check
  ping:

# Checking that hosts are running a supported release
- name: Check correct running release on hosts
  assert:
    that: "ansible_distribution_version >= '7.5' and (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS')"
    msg: "Your host OS release is not RedHat 7.5 or CentOS 7.5"

# Adding SSH Key from the local machine to the hosts when inject_ssh_key variable is true
- name: Adding the SSH Key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', ssh_local_key_path) }}"
  when: inject_ssh_key
  notify: Testing SSH with Key
 
# Setting the hostname on the hosts based on the inventory name
- name: Setting the hostname
  hostname:
    name: "{{ inventory_hostname }}"