---
# Disabling firewalld on the host when disable_firewalld variable is true
- name: Stopping and disabling the firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: disable_firewalld

# Disabling firewalld on the host when disable_selinux variable is true
- name: Setting selinux to disabled state
  selinux:
    state: disabled
  register: teste
  when: disable_selinux