---
# Handler for basic.yml task "Adding the SSH Key"
- name: Testing SSH with Key
  local_action: shell ssh root@{{ hostvars[inventory_hostname].ansible_host }}

# Handler for networking.yml task "Setting the DNS servers"
- name: Testing network and DNS
  uri:
    url: http://www.google.com

# Handler for repository.yml task "Adding EPEL repository"
- name: YUM clean metadata
  command: yum clean metadata
  args:
    warn: no